### ISSUE TITLE
organizations json for browse-orgs

### ISSUE THREAD

**Issue by evanwill** [uidaholib/inside_source#22]
@kandersonko I added an example json template in `/assets/data/organizations.json` based on simplified structure of the old json from the ArcGIS API,
https://github.com/uidaholib/inside_source/blob/master/assets/data/organizations.json

When the site is built, it will be available at `/assets/data/organizations.json`

You can redo the template however you like, or let me know what you would like there.

**Comment by kandersonko** [comment]
Thanks! I am using it now it the apps.
