### ISSUE TITLE
js app compontents style integration

### ISSUE THREAD

**Issue by evanwill** [uidaholib/inside_source#24]
@kandersonko following up on conversations about integrating the app js bundles into the inside jekyll template (sorry if repeating some things :smile: ):

Since this isn't a stand alone JS app any more, the styling should be handled by the inside_source template. Currently it looks like some of the app loads component parts from Tailwind scss? The app shouldn't have to load any css style rules, it can just use bootstrap classes directly (since it is already loaded on the page, and will make for a more consistent template). 

Jekyll will take each content page, and wrap it in the template, so basically search.md, browse-org.md, and browse-framework.md will become:

```
[head, nav template stuff]
<main id="maincontent" role="main">
  <div class="container mt-4">
    <h1 class="text-center">Page Title</h1>
    <div id="inside-browse-org"></div>
  </div>
</main>
[footer, js template stuff, including loading the app bundle]
```

Thus, the js bundles are adding the form and results content only to the div on the page. Again, since it is now integrated into the existing page (following a much less sophisticated framework!), the mark up added by the bundle should be simplified:

- [x] shouldn't add a page title, that should be handled by the .md stub for simplicity
- [x] shouldn't add a `<main>` element, since it is already inside one on the page.
- [x] should probably use basic bootstrap [row+col grid layout](https://getbootstrap.com/docs/4.4/layout/grid/) for consistency 
- [x] results items should probably use bootstrap [card component](https://getbootstrap.com/docs/4.4/components/card/) for consistency 
- [x] no drop shadow since we don't use it anywhere else
- [x] I would rather see links `<a href="">` rather than buttons using js to act as links. Actual links are usually more user friendly and easy for accessibility.

**Comment by evanwill** [comment]
I added an draft-y template of what I imagine the form + results template mark up might look like in [docs/example-template.html](https://github.com/uidaholib/inside_source/blob/master/docs/example-template.html). This is the basic style similar to our other card item results and base bootstrap, fairly simplistic. Just an idea, not necessary to implement exactly like this!

**Comment by kandersonko** [comment]
I think we are set with the Javascript apps integration. Thanks.
