### ISSUE TITLE
Incorrect Results in Browse Framework App

### ISSUE THREAD

**Issue by b-godfrey** [uidaholib/inside_source#42]
https://insideidaho.org/browse-framework.html does not appear to be returning the correct results.

We should be getting these 3 results:
https://hub.arcgis.com/search?tags=idaho%20geospatial%20council%20-%20executive%20committee%20(igc-ec)%20framework%20layer

See here also via ArcGIS Online:
https://www.arcgis.com/home/search.html?t=content&q=tags%3A%22Idaho%20Geospatial%20Council%20-%20Executive%20Committee%20(IGC-EC)%20Framework%20Layer%22

**Comment by kandersonko** [comment]
This should be fixed in #44.

**Comment by kandersonko** [comment]
@b-godfrey Let me know if the fix works so that I can close this issue. Thanks.

**Comment by b-godfrey** [comment]
Hi Koffi, the correct results are being returned.  One thing looks odd though.  The HTML tags in the description are showing up (see image below).  If I use the search app for ‘framework’ I don’t see the HTML tags in the results.  Could you check that in browse framework?   Bruce

[cid:image002.jpg@01D68AA8.973AF2D0]

**Comment by kandersonko** [comment]
I am using version 3 now instead of version 2 of the open data API. That's why it showing HTML tags. I am going to fix that. Thanks.

**Comment by kandersonko** [comment]
I have fixed that issue with #45.
