### ISSUE TITLE
Behavior of Search app filters

### ISSUE THREAD

**Issue by b-godfrey** [uidaholib/inside_source#52]
https://insideidaho.org/search.html?q=water

There are no choices in the 'Type' filter.  

Also, let's discuss the 'Organization' filter results.  I'd like to understand more about the property/properties we are using for 'data provider' and 'organization'.

**Comment by kandersonko** [comment]
- [x] Make search filter organization consistent with the organization name displayed in the browse orgs (Koffi - please keep the code you currently have along with the new code you write.  We may end up using what you currently have so it will be best to have two options depending on which direction we go.)

**Comment by kandersonko** [comment]
Fixed in #53.
