### ISSUE TITLE
Scaffold site

### ISSUE THREAD

**Issue by dcnb** [uidaholib/inside_source#6]
- [x] new search/browse bar
- [x] Carousel on front page
- [x] Sections on front page

**Comment by dcnb** [comment]
@b-godfrey I made a big push at the home page, Bruce. Let me know what you think. Needs a lot of content overall, but added a decent amount. 

Still need to do a carousel like libraries. I think that should look good. Might end up cutting that featured row if that's the case though--there's a lot of 'featured'.  I also think it'd be cool to somehow list ALL the many ArcGIS options available on that front page.

**Comment by b-godfrey** [comment]
Hi Devin, I'll take a look first thing tomorrow.  I've been working on it as well this week getting to know the structure and working with some content.  I was just talking with Olivia today about the carousel.  I'll make sure to make a copy of my changes and then grab yours and go from there.  Thanks!   -Bruce

________________________________

**Comment by dcnb** [comment]
@b-godfrey added the markup for the new images! Looking good!

**Comment by b-godfrey** [comment]
Nice! Thank you.  -Bruce
